open5gs-master: drop unknown option metrics_impl
The metrics_impl option has been dropped in the related commit as
prometheus is now the default in open5gs. With newer meson, unknown
options are treated as errors (used to be warnings before).

Fix for:
ERROR: Unknown options: "metrics_impl"

Related: OS#6057
Related: https://github.com/open5gs/open5gs/commit/982ac61894ba5ac7b532661773df0cae859bb4f1
Change-Id: Ib859ef7389928019addecae08df2011eecda80ad