debian-*-jenkins: git clone from gerrit
Avoid occasional clone failures by replacing https://git.osmocom.org
with https://gerrit.osmocom.org.

  Step 18/28 : RUN git clone https://git.osmocom.org/osmo-ci osmo-ci && 	cp -v $(find osmo-ci/scripts 		-maxdepth 1 		-type f ) 	   /usr/local/bin
   ---> Running in c1c0bc9fb861
  Cloning into 'osmo-ci'...
  error:  (curl_result = 56, http_code = 200, sha1 = ded2f31cbac2e7b0ae6c3c4147f4e21ab1ce9b98)
  error: Unable to find ded2f31cbac2e7b0ae6c3c4147f4e21ab1ce9b98 under https://git.osmocom.org/osmo-ci
  Cannot obtain needed tree ded2f31cbac2e7b0ae6c3c4147f4e21ab1ce9b98
  while processing commit bff275075548c443596aa1eb80d784e4cd3c2231.
  error: fetch failed.

Related: SYS#5857
Change-Id: I9ad8e5755c5d520ff33d85792a5a70da62d05253